alias gts='git status'
alias gta='git add'
alias gtc='git commit -m'
alias gtac='git add . && git commit -m'
alias gtpl='git pull'
alias gtps='git push'
alias seba='source $HOME/env/bin/activate'
alias gen-ini='python3 ~/data/scripts/data-generation/generate-config.py'