SPARQL
PREFIX rr: <http://www.w3.org/ns/r2rml#> 
PREFIX rml: <http://semweb.mmlab.be/ns/rml#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX ql: <http://semweb.mmlab.be/ns/ql#> 
PREFIX map: <http://mapping.example.com/> 
PREFIX ma: <http://www.w3.org/ns/ma-ont#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX rev: <http://purl.org/stuff/rev#> 
PREFIX v: <http://rdf.data-vocabulary.org/#> 
PREFIX schema: <http://schema.org/> 
PREFIX gtfs: <http://vocab.gtfs.org/terms#> 
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> 
PREFIX dct: <http://purl.org/dc/terms/> 


SELECT ?stopCodeStekenedl ?departureTimeSTdl ?stopCodeSNdl ?departureTimeSNdl ?stopSNnmbs ?bluebikeSN ?departureTimeSNnmbs ?stopGSPnmbs ?departureTimeGSPnmbs ?bluebikeGSP ?tripname ?nameGSPdl ?departureTimeGSPdl ?nameIMECdl ?departureTimeIMECdl #?tripSNGSP 
WHERE {
    #########################################################
    ## Part De Lijn Gent-Sint-Pieters to IMEC AA-Tower
    #########################################################

    #details stop GSP delijn
    ?stopGSPdl a gtfs:Stop ;
        foaf:name ?nameGSPdl ;
        gtfs:code 204917 .       #station gent sp

    #details stop IMEC delijn
    ?stopIMECdl a gtfs:Stop ;
        foaf:name ?nameIMECdl ;
        gtfs:code 200659 .        #zwijnaarde technologiepark

    #details trip GSP IMEC delijn
    ?tripGSPIMEC a gtfs:Trip .
        # gtfs:route ?route ;
        # # gtfs:direction ?direction ;
        # dct:identifier ?tripGSPIMECId .

    ?stopTimeGSPdl a gtfs:StopTime ;
            gtfs:stop ?stopGSPdl ;
            gtfs:trip ?tripGSPIMEC ;
            gtfs:departureTime ?departureTimeGSPdl ;
            gtfs:stopSequence ?seqGSPdl .

    ?stopTimeIMECdl a gtfs:StopTime ;
            gtfs:stop ?stopIMECdl ;
            gtfs:trip ?tripGSPIMEC ;
            gtfs:departureTime ?departureTimeIMECdl ;
            gtfs:stopSequence ?seqIMECdl .

    FILTER (?departureTimeIMECdl >= "2023-02-21T08:00:00"^^xsd:dateTime && ?departureTimeIMECdl <= "2023-02-21T09:00:00"^^xsd:dateTime)
    FILTER (?departureTimeGSPdl >= "2023-02-21T00:00:00"^^xsd:dateTime && ?departureTimeGSPdl <= "2023-02-21T09:00:00"^^xsd:dateTime)
    FILTER(?seqGSPdl < ?seqIMECdl)

    # # BIND ( (?departureTimeGSPdl - 300) AS ?bufferGSPdl)    #buffer to have time to transfer from train to bus

    #########################################################
    ## Part NMBS Sint-Niklaas to  Gent-Sint-Pieters
    #########################################################

    #start location
    ?stopSNnmbs foaf:name "Sint-Niklaas";
        a gtfs:Stop ;
        gtfs:bikeAllowed ?bluebikeSN .

    ?stopGSPnmbs foaf:name "Gent-Sint-Pieters" ;
        a gtfs:Stop ;
        gtfs:bikeAllowed ?bluebikeGSP .

    ?stopTimeSNnmbs a gtfs:StopTime;
        gtfs:stop ?stopSNnmbs ;
        gtfs:trip ?tripSNGSP ;
        gtfs:departureTime ?departureTimeSNnmbs ;
        gtfs:stopSequence ?seqSNnmbs .

    ?stopTimeGSPnmbs a gtfs:StopTime;
        gtfs:stop ?stopGSPnmbs ;
        gtfs:trip ?tripSNGSP ;
        gtfs:departureTime ?departureTimeGSPnmbs ;
        gtfs:stopSequence ?seqGSPnmbs .

    ?tripSNGSP a gtfs:Trip ;    
        gtfs:headsign ?tripname .

    FILTER (?departureTimeGSPnmbs >= "2023-02-21T07:15:00"^^xsd:dateTime && ?departureTimeGSPnmbs <= "2023-02-21T08:30:00"^^xsd:dateTime) 
    FILTER (?departureTimeSNnmbs >= "2023-02-21T00:00:00"^^xsd:dateTime && ?departureTimeSNnmbs <= "2023-02-21T08:15:00"^^xsd:dateTime) 
    FILTER (?seqGSPnmbs > ?seqSNnmbs) # to have the correct direction for the trip

    # #########################################################
    # ## Part De Lijn Stekene to Sint-Niklaas
    # #########################################################

    ?stopStekenedl a gtfs:Stop ;
            # foaf:name "Stekene Kerk" ;
            foaf:name ?stopCodeStekenedl ;
            gtfs:code 204391 .
            # gtfs:code ?stopCodeStekenedl .

    ?stopSNdl a gtfs:Stop ;
            # foaf:name "Sint-Niklaas Uitgang Noordlaan" ;
            foaf:name ?stopCodeSNdl ;
            gtfs:code 204714 .
            # gtfs:code ?stopCodeSNdl .
    
    ?tripSTSN a gtfs:Trip .
    #     gtfs:route ?route ;
    #     gtfs:direction ?direction ;
    #     dct:identifier ?tripId .

    ?stopTimeStekenedl a gtfs:StopTime ;
            gtfs:stop ?stopStekenedl ;
            gtfs:trip ?tripSTSN ;
            gtfs:departureTime ?departureTimeSTdl ;
            gtfs:stopSequence ?seqSTdl .
    FILTER (?departureTimeSTdl >= "2023-02-21T00:00:00"^^xsd:dateTime && ?departureTimeSTdl <= "2023-02-21T08:00:00"^^xsd:dateTime)
    
    ?stopTimeSNdl a gtfs:StopTime ;
            gtfs:stop ?stopSNdl ;
            gtfs:trip ?tripSTSN ;
            gtfs:departureTime ?departureTimeSNdl ;
            gtfs:stopSequence ?seqSNdl .
    FILTER (?departureTimeSNdl >= "2023-02-21T07:00:00"^^xsd:dateTime && ?departureTimeSNdl <= "2023-02-21T08:00:00"^^xsd:dateTime)

    FILTER(?seqSTdl < ?seqSNdl)

} ORDER BY ?departureTimeGSPdl ?departureTimeIMECdl;